trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "My first Azure pipeline project"
  displayName: 'Run a one-line script'

- script: |
    mvn clean install
    echo "Add other tasks to build, test, and deploy your project."
    echo "See https://aka.ms/yaml"
  displayName: 'Build with Maven'

- script: java -jar target/MAV-1.0-SNAPSHOT.jar
  displayName: 'Run JAR file'
